appname: Sinatra DEFAULT development
database:
  name: exporter
  user: postgres
  password: postgres
dm_reports_location: lib/exporter/dataminer_sources
dm_js_location: assets
dm_css_location: assets
